seanmonstar/httparse

- src/lib.rs
The headers buffer and the buffer we are parsing from can
now have two distinct lifetimes.
> use two lifetime parameters to be more permissive

- Cargo.toml
- src/lib.rs
All HTTP/1.1 clients and servers must understand the chunked encoding
and therefore must parse chunk sizes. The `parse_chunk_size` function
uses relies on the internals of httparse so it can't be implemented as
easily in an external crate. It is based on hypers implementation but
unlike hyper it operates on &[u8] and returns partial if the chunk size
is incomplete. For this reason it is more suitable for async HTTP code.
This is a breaking change because it adds a new variant to the Error
enum.
> impl a function to parse chunk sizes

- src/lib.rs
Previously requests of the form `GET\n/ HTTP/1.1\r\nHost: foo.bar\r\n\r\n` would parse.
> Stop parsing requests with invalid method or path delimiters

- src/iter.rs
- src/lib.rs
Thanks to the no-copy design, this crate has no dependencies on things in `std`, and it's trivial to make it work with `no_std` configuration.
> Don't use std

- src/lib.rs
So that the errors can be passed to any macro/function that expects the Display trait.
Ideally these error types would also implement the Error trait, but that would require the std crate.
> Implement Display for Error and InvalidChunkSize

- src/lib.rs
> parse responses that do not include a reason phrase

- src/simd/avx2.rs
As reported in #42, the `_tzcnt_u64` function isn't defined on `x86`, and so causes compilation errors. As a quick fix, this simply disables avx2 on that arch.
> disable avx2 on 32bit archs temporarily

- Cargo.toml
Using a dependency with required version 0.0 can cause issues with semver as updates are not guaranteed to be backwards compatible.
> Set specific version of pico-sys in Cargo.toml

- src/lib.rs
`&` applied to two booleans is the non-short-circuiting logical AND. That works here, but `&&` is probably what was intended.
> Correct `&` to `&&`

- src/iter.rs
If len = pos + 8, then there are exactly eight bytes available.
> Fix off-by-one error

- src/lib.rs
The derivation on Header is correct because comparisons of string slices and byte slices meet the requirements. The derivations on Request and Response are correct because they contain only string slices, byte slices, slices of Header objects (which are now Eq), primitives, and options (which are Eq if their contents are). Finally the derivation on Status is correct because #[derive(Eq)] on a generic only actually implements Eq if all generic parameters are Eq, which for Status is sufficient.
> Add missing Eq derivations

- fuzz/.gitignore
- fuzz/Cargo.toml
- fuzz/fuzz_targets/parse_chunk_size.rs
- fuzz/fuzz_targets/parse_headers.rs
- fuzz/fuzz_targets/parse_request.rs
Reading https://lobste.rs/s/bfjdfd/rust_curl_with_hyper#c_r8wiua made me curious to do some basic fuzzing on this crate using `cargo-fuzz`. None of the included targets found anything interesting though, which is good. Perhaps we should try to target the SIMD code directly, by exposing it publicly with a `fuzzing` feature or something like that?
> Basic fuzzing using cargo-fuzz

- src/lib.rs
Just a doc comment so people don't have to read through parse's implementation to know what its return value is.
> Describe return of parse function.

- src/lib.rs
- tests/uri.rs
The status code would previously be folded into the first header name.
> Fix parsing responses with no CRs

- build.rs
- src/lib.rs
- src/macros.rs
- src/simd/mod.rs
Now that we require at least Rust 1.36, we can fix up some deprecations.
> Fix up some deprecations

- README.md
cf. https://docs.rs/httparse/1.3.4/httparse/constant.EMPTY_HEADER.html#example
> Fixes #70 - Update README to be consistent with docs example

- src/lib.rs
Rather then looking at a slice of bytes is easier (for most humans) to
read a string. Since most, but not all, header values are strings
attempt to create a string from the header value and print that, falling
back to printing it a slice of bytes if the value is not a valid UTF-8
string.
> Print Header value as string if it's UTF-8

- src/simd/avx2.rs
- src/simd/sse42.rs
The SIMD intrinsics *_cmpgt_epi8 are for signed chars.
This change correctly performs the unsigned comparison.
> Fix SIMD header value check on char >= 0x80

- src/iter.rs
- src/lib.rs
- src/simd/avx2.rs
- src/simd/sse42.rs
For reference, this was the clippy output:
```
warning: redundant field names in struct initialization
--> src/iter.rs:12:13
|
12 |             slice: slice,
|             ^^^^^^^^^^^^ help: replace it with: `slice`
|
= note: `#[warn(clippy::redundant_field_names)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_field_names
warning: unnecessary `>= y + 1` or `x - 1 >=`
--> src/iter.rs:29:23
|
29 |         debug_assert!(self.pos + 1 <= self.slice.len(), "overflow");
|                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: change it to: `self.pos < self.slice.len()`
|
= note: `#[warn(clippy::int_plus_one)]` on by default
= help: for further information visit …
```
> Fix clippy warnings for Rust 1.59

- src/lib.rs
- tests/uri.rs
This fixes cases where the parser would accept non-compliant request lines including empty methods and paths.
For the `token` grammar, [the spec][spec-token] is:
```
token          = 1*tchar
```
`1*` is shorthand for one-or-more, so the empty string is not a valid `token`.
For the path component of the request line, [the spec][spec-path] we're concerned with the `absolute-path` grammar:
```
absolute-path = 1*( "/" segment )
```
While `segment` might be empty, there must be at least a `"/"` for it to be syntactically valid.
I've added tests for these cases and their combination, and had to update the expected error of one of the existing URI tests which now fails sooner due to the empty path.
[spec-token]: https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#tokens …
> Fix token and uri parsers to disallow empty results

- .github/workflows/ci.yml
- build.rs
This only works if we use the fallback implementation with Miri.
(FWIW, using `core::simd` would work, but `core::arch` simply has too many intrinsics to support them all in Miri.)
> run Miri on CI

- src/lib.rs
Depends on #111.
These new flags set whether multiple spaces are allowed as delimiters in request lines and response status lines.
The latest version of the HTTP/1.1 spec ([request lines][spec-req], [response status lines][spec-resp]) allows implementations to parse multiple whitespace characters in place of the `SP` delimiter in the response status line, including:
> SP, HTAB, VT (%x0B), FF (%x0C), or bare CR
This option relaxes the parsers to allow for multiple spaces, but does *not* allow the delimiters to contain the other mentioned whitespace characters. We'd rather wait for someone to have a concrete use case before deciding to support that, as allowing chars like `\r` raises serious security questions as described by the spec.
[spec-req]: …
> Add flags to allow multiple spaces in request and status lines

- src/iter.rs
- src/lib.rs
Special-case parsing of the GET request method as that is by far the
most common. Speeds up the req_short benchmark by a fair margin:
req_short/req_short     time:   [32.601 ns 32.737 ns 32.914 ns]
thrpt:  [1.9241 GiB/s 1.9345 GiB/s 1.9425 GiB/s]
change:
time:   [-4.1113% -3.5415% -3.0150%] (p = 0.00 < 0.05)
thrpt:  [+3.1087% +3.6715% +4.2876%]
Performance has improved.
Co-authored-by: Luca Casonato <hello@lcas.dev>
> Improve request method parsing

- src/iter.rs
- src/lib.rs
Also improves performance, mainly `parse_version`, we observe a ~10% improvement on `req_short`:
```
req_short/req_short     time:   [29.214 ns 29.296 ns 29.391 ns]
thrpt:  [2.1548 GiB/s 2.1617 GiB/s 2.1678 GiB/s]
change:
time:   [-10.968% -9.6366% -7.9937%] (p = 0.00 < 0.05)
thrpt:  [+8.6882% +10.664% +12.319%]
Performance has improved.
```
> cleanup: remove Bytes8 abstraction

- Cargo.toml
- benches/parse.rs
- src/iter.rs
- src/lib.rs
- src/simd/avx2.rs
- src/simd/fallback.rs
- src/simd/mod.rs
- src/simd/sse42.rs
- tests/uri.rs
Due to `MaybeUninit`, the crate already wasn't compatible with any pre-2018 Rust version.
> Edition 2018

- .github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz where httparse already runs. CIFuzz can help detect regressions and catch fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.
> ci: Add CIFuzz GitHub Action

- benches/parse.rs
- src/iter.rs
- src/lib.rs
To provide better baselines for perf work, etc...
It unfortunately requires exposing a few functions as public, though they are hidden from the docs and re-exported under a `_benchable` mod
I wanted to land this first to have a solid baseline to frame the other performance improvements I'll submit shortly
```
test req/req ... bench:                 223 ns/iter (+/- 8)
test req_short/req_short ... bench:     29 ns/iter (+/- 0)
test resp/resp ... bench:               212 ns/iter (+/- 4)
test resp_short/resp_short ... bench:   35 ns/iter (+/- 1)
test uri/uri_1b ... bench:              0 ns/iter (+/- 0)
test uri/uri_2b ... bench:              1 ns/iter (+/- 0)
test uri/uri_4b ... bench:              2 ns/iter (+/- 0)
test uri/uri_8b ... bench:              3 ns/iter (+/- 0)
test uri/uri_16b …
```
> Improve granularity of benchmarks

- src/lib.rs
A 1st pass at improving non-SIMD perf, to land after https://github.com/seanmonstar/httparse/pull/122
On aarch64/M1 we observe a ~5x asymptotic improvement in uri parsing and ~2.5x in header names & values.
We also observe a -40% time reduction in the `req/req` bench.
I briefly benched it on x86_64, we see a -20% time reduction in the `req/req` bench there for non-SIMD, needs more testing/tweaks on x86_64 and possibly only enabling these fastpaths if SIMD is off
```
test req/req ... bench:         145 ns/iter (+/- 2)
test req_short/req_short ... bench:          30 ns/iter (+/- 3)
test resp/resp ... bench:         153 ns/iter (+/- 6)
test resp_short/resp_short ... bench:          35 ns/iter (+/- 0)
test uri/uri_1b ... bench:           1 ns/iter (+/- 0)
test uri/uri_2b ... bench: …
```
> perf: improve non-SIMD with wordwise validation 

- Cargo.toml
- src/simd/avx2.rs
- src/simd/sse42.rs
Drastically improving throughput on larger inputs (3x+ for large URIs or header-values)
There are 2 optimizations in this PR:
1. Removing two unnecessary instructions when computing trailizing_zeros / bytes-validated.
We don't need to `or` the upper half of the register with `xFF` we can instead compute trailing-zeros on the meaningful bits by using `eax` (`u32`) instead of `rax` (`u64`) and `ax` (`u16`) instead of `eax` (`u32`) for AVX2 and SSE4.2 respectively.
2. Correctly scoping `target_feature` pragmas to allow SIMD validators to be inlined, so when looped we benefit from greater register reuse etc... See:
- https://doc.rust-lang.org/reference/attributes/codegen.html#the-target_feature-attribute
- https://rust-lang.github.io/rfcs/2045-target-feature.html
(Disclaimer: aggregated by …
> perf: fix SIMD-inlining

- src/simd/avx2.rs
- src/simd/mod.rs
- src/simd/runtime.rs
- src/simd/sse42.rs
Also cleanup, builds off #131
We can see the overhead improvements in uri parsing for smaller values (where overhead is relatively significant) and we can see it compound in header/count accumulating the overhead of jumping in & out of SIMD.
|         | 1   | 2   | 4   | 8   | 16  | 32  | 64  | 128 |
|---------|-----|-----|-----|-----|-----|-----|-----|-----|
| Before | 22  | 39  | 77  | 144 | 283 | 578 | 1092| 2159|
| After  | 21  | 37  | 71  | 135 | 271 | 568 | 1025| 2034|
|         | 1b  | 2b  | 4b  | 8b  | 16b | 32b | 64b | 128b | 256b | 512b | 1024b | 2048b | 4096b |
|---------|-----|-----|-----|-----|-----|-----|-----|------|------|------|-------|-------|-------|
| Before | 7   | 8   | 9   | 11  | 8   | 6   | 7   | 11   | 19   | 34   | 67    | 127   | 270   |
| After  | 5   | 5   | …
> cleanup: SIMD runtime detection

- src/lib.rs
Instead of static constants for GET/POST, fixes #124
> fix: return method string from buffer

- .github/workflows/ci.yml
- src/simd/mod.rs
- src/simd/neon.rs
First pass at neon support, building off #132
I shared some promising benches here: https://github.com/seanmonstar/httparse/pull/123#issuecomment-1509870871
Overall it's a net-positive but not totally optimal.
Next steps we would want to land #123 and then refactor it into a SWAR SIMD backend and stack them appropriately to avoid duplicated work and cleaner logic.
Additionally, offsetz is very much central to total perf, I believe the vectorized implementation I added underperforms due to inefficiently reloading the offset lookup table instead of keeping it a register at the top of the header parsing loop.
> perf: simd neon

- src/iter.rs
IMO cleaner pointer arithmetic avoiding unnecessary intermediate slices.
No perf gains in isolation but facilitates some (upcoming PRs)
This is conceptually easier to reason about, end is fixed, "start" and "cursor" advance monotonically
> refactor: Bytes inner arithmetic

- .github/workflows/ci.yml
- build.rs
- src/simd/mod.rs
First commit should intentionally fail in CI, then use a cfg guard to fallback to `swar` instead of `neon`
NOTE: on M1 `swar` is surprisingly "only" ~30% slower than `neon` (i.e: `~100ns/iter` vs `~70ns/iter` for `req/req`).
Unblocks #141 (since we can punt raising MSRV)
> msrv: test aarch64

- src/simd/avx2.rs
- src/simd/sse42.rs
```
before:
test header/value_256b ... bench:          34 ns/iter (+/- 13)
test header/value_512b ... bench:          50 ns/iter (+/- 5)
test header/value_1024b ... bench:          86 ns/iter (+/- 7)
test header/value_2048b ... bench:         172 ns/iter (+/- 20)
test header/value_4096b ... bench:         298 ns/iter (+/- 62)
after:
test header/value_256b ... bench:          33 ns/iter (+/- 10)
test header/value_512b ... bench:          48 ns/iter (+/- 20)
test header/value_1024b ... bench:          77 ns/iter (+/- 8)
test header/value_2048b ... bench:         149 ns/iter (+/- 8)
test header/value_4096b ... bench:         252 ns/iter (+/- 50)
```
> simd: drop 2 unnecessary instructions

- src/simd/neon.rs
I accidentally typed `std::mem` out of habit, this wasn't caught in #133 because `neon+no_std` isn't exercised
> fix: neon no_std

- src/lib.rs
- src/macros.rs
The idea for this PR came up from [this](https://github.com/hyperium/hyper/discussions/3267) discussion in the hyper repo.
This PR tries to make a request version of the `ParserConfig::ignore_invalid_headers_in_responses` configuration, introduced as `ParserConfig::ignore_invalid_headers_in_requests`, so that we can also ignore invalid headers in requests.
In order to achieve that avoiding breaking backwards compatibility, it splits the `ParserConfig` struct used for `parse_headers_iter_uninit` into `ParserConfig` and `HeaderParserConfig`.
Happy to reassess the tests or the approach.
> Ignoring invalid headers for requests

- src/lib.rs
Adds support for for ignoring leading whitespace in response header as requested in this [issue](https://github.com/hyperium/hyper/issues/3285)
> Add option to allow space before first header name

- benches/parse.rs
This has the effect of slowing down many of the benchmarks, which implies that the compiler has been able to constant-fold some of the computations.
I'm submitting this as its own PR, as any future changes (of which I have one pending) should be evaluated based on these more complete benchmarks, rather than on how well the compiler can constant fold after the changes.
I ran both before and after with Criterion default settings, as my hardware gives more consistent results with the defaults.  This is what I got:
```
req/req                 time:   [195.98 ns 197.50 ns 199.22 ns]
thrpt:  [3.3658 GiB/s 3.3952 GiB/s 3.4215 GiB/s]
change:
time:   [+1.5871% +2.6429% +3.7379%] (p = 0.00 < 0.05)
thrpt:  [-3.6032% -2.5749% -1.5623%]
Performance has regressed.
Found 3 outliers among 100 …
```
> Apply black_box to known bench inputs

- src/lib.rs
- src/simd/avx2.rs
- src/simd/mod.rs
- src/simd/neon.rs
- src/simd/runtime.rs
- src/simd/sse42.rs
- src/simd/swar.rs
This refactors all SIMD modules in order to make the value-matching logic self-contained. Thus, all bytes-cursor manipulations are now grouped and performed once at the end, outside of SIMD logic.
Performance impact on my AVX2-capable workstation seems positive (arbitrary benchmark-noise filtering at >20%):
> simd: split cursor advancing from value matching

- .github/workflows/ci.yml
- src/simd/avx2.rs
> fix compilation on x86

- src/lib.rs
- src/simd/avx2.rs
- src/simd/mod.rs
- src/simd/neon.rs
- src/simd/runtime.rs
- src/simd/sse42.rs
- src/simd/swar.rs
It was noticed with a bisect the bug was introduced in this commit, so I'm reverting it for now to get a fix out faster.
cc @lucab 
Fixes #172 
Fixes #173
> Fix no space after colon

- src/lib.rs
A regression was introduced [in this bit of the SWAR changeset](https://github.com/seanmonstar/httparse/pull/134/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759L969-R882) which manifests as incorrectly classifying a `read()` with the contents `GET ` as a token error (because there's no characters yet to parse for the path part) rather than as an `Ok(Status::Partial)`.
This diff is three independent commits to:
1. Add specific regression tests covering this and similar situations
2. Add a general regression test checking all permutations of a partial one-line request
3. Fix the behavior of the `parse_uri()` function to disambiguate between an empty path followed by a space, versus a partial read that ends at the start of the path.
NB. This'll conflict with #175 …
> Test and fix a regression in parsing partial requests in the 1.9.x series

- .github/workflows/cibench.yml
First pass at adding benchmarks in CI.
Covers matrix of key archs and SIMD extensions.
Outputs delta against `main` with `critcmp` (with 5% noise threshold).
- Run classifier on results to indicate regression/improvement/neutral (aggregate or on specific arch)
- Post summary (or details if regression) as PR comment (didn't add cause without summary would be noisy)
- Could save `main` baselines as assets (and just ref/download them) instead of recomputing them for each PR
(comes at a cost of statefulness and some adhoc complexity but would reduce CI time cost)
- This adds CI (compute) time, but don't think it adds wall time since there are longer subtasks
- CI is still more noisy than controlled local env, but probably good enough for substantial perf changes and sanity-checking
> perf: cibench workflow

- benches/parse.rs
Small nit, but facilitates reading benchmark outputs, especially through `critcmp` follow-up to #179 
zero-pad bench names derived from payload size to improve  lexicographic sorting (order matches payload size)
> benches: lexicographically ordered bench names

- src/simd/avx2.rs
**TLDR:** 2-line change => 2x faster `req/req`
(doesn't raise the ceiling substantially but fixes perf issue of generic x64 build, using runtime dispatch)
This has massive implications on the default `simd::runtime::*` (x64 generic build) perf, improving how the code is lowered/inlined. (Falling back to SSE4.2 for a handful of bytes was wasteful).
Should supersede #175, #156
(4 cores of a 64-core AMD EPYC 7763 host CPU)
```
> critcmp -t=5 main avx2swar
group                    avx2swar                               main
-----                    --------                               ----
header/count_001         1.00     21.8±3.10ns   349.2 MB/sec    6.14   134.0±11.80ns    56.9 MB/sec
header/count_002         1.00     31.9±4.18ns   418.7 MB/sec    7.95    253.5±8.07ns    52.7 MB/sec …
```
> perf(simd): avx2 fallback to swar instead of sse4.2

- src/simd/mod.rs
simd::avx2 no longer calls simd::sse42, so we shouldn't build it when compiling for +avx2
follow-up to #181 (didn't pay attention to warnings of unused code)
> lint(simd): don't build simd::sse42 when +avx2

- src/iter.rs
No functional changes intended.
From [the docs of pointer::add](https://doc.rust-lang.org/std/primitive.pointer.html#method.add): 
>If the computed offset is non-zero, then self must be derived from a pointer to some [allocated object](https://doc.rust-lang.org/std/ptr/index.html#allocated-object), and the entire memory range between self and the result must be in bounds of that allocated object. In particular, this range must not “wrap around” the edge of the address space.
> fix unsound use of pointer::add

- Cargo.toml
- benches/parse.rs
- src/lib.rs
- src/simd/neon.rs
The `is_token` function, used exclusively for parsing the method in a request line, allows more values than it should. In particular, it allows a leading space to be parsed.  This problem is not exposed in hyper, which revalidates any method extracted by httparse, otherwise I'm sure this would have been noticed sooner!
Checking for a single range of valid bytes is very fast, so I've taken care to make sure that making `is_token` more complicated doesn't slow down the most common case.  While exploring a variety of options, I found the existing benchmark scheme to be a bit misleading because it would test only a single method at a time, so I've made a new benchmark that roughly simulates a mix of requests.  Ultimately, what I found to be a reasonable fix without any slowdown for the …
> Fix method parsing

- .github/workflows/ci.yml
1.47 is about 4 years old and is needed for `offset_from` in #187.
> Update MSRV from 1.36 to 1.47

- src/iter.rs
`self.cursor.sub(skip)` must point inside the allocation of this object or this is UB, not to mention the possibility that if `skip` is very large self.cursor.sub(skip) may underflow and fail to trigger the debug_assertion.
> iter::slice_skip remove possibility of underflow in debug_assert

- src/lib.rs
- src/simd/avx2.rs
- src/simd/neon.rs
- src/simd/sse42.rs
- src/simd/swar.rs
Ref https://github.com/seanmonstar/httparse/issues/146
I'm not used to work with simd parser so i have done what i think is right but not sure if it's right in all use case.
Mainly the uri non compliant rfc3986 parser is the same as the current one but allow every char between 128 to 255 which sould make it utf8 compliant, if i recall correctly code point always are above or equal to 128
I did not make a feature but rather an option in parser, however i wonder if this should be true by default ? or if it should be a feature (enabled by default ?) ?
> feat(path): allow utf8 chars in path

- src/iter.rs
- src/lib.rs
This fixes the inadequate safety checks, by checking the index `n` against the length of the byte array. Then there is no need to use wrapping_add instead of add since we now never point outside the array (since we checked the index against length already).
Potentially, there is some performance impact here, but the benchmarks are not very clear about the direction. Perhaps there is none to speak of?
> Fix unsoundness of peek_ahead in iter.rs

- src/simd/avx2.rs
> chore(docs): document the AVX2 instructions

- src/simd/avx2.rs
- src/simd/swar.rs
This supersedes #202 and closes #201. SWAR validator now allows UTF8 characters as other SIMD backends. Tests are also updated.
> fix(swar): utf8 support

- build.rs
- src/iter.rs
- src/lib.rs
- src/simd/avx2.rs
- src/simd/sse42.rs
- src/simd/swar.rs
Update to use APIs which are available now that the [MSRV is 1.47](https://github.com/seanmonstar/httparse/pull/192):
- `{integer}::from_ne_bytes` const since 1.44
- `{integer}::trailing_ones` stable since 1.46
- `str::strip_prefix` stable since 1.45
> Update to use APIs up to MSRV
